### ISSUE TITLE
Is there a timeout ?

### ISSUE THREAD

**Issue by pirquessa** [kaimallea/node-googl#13]
Thanks for this cool module !

Does it have a timeout feature to prevent waiting to long for a conversion ?

**Comment by pirquessa** [comment]
Found 

`googl.shorten(url, {timeout: 10})`

:)

**Comment by keithnorm** [comment]
I don't think that actually works. The second param of `shorten` gets appended to the post body of the `goo.gl` request. There doesn't seem to be a way to specify the timeout option for the `request` on the caller's side as far as I can tell.

**Comment by pirquessa** [comment]
Seems to be working for me after a few tests...
