### ISSUE TITLE
Project activeness

### ISSUE THREAD

**Issue by DiegoRBaquero** [kaimallea/node-googl#19]
Hey Kai,

I've noticed that the project has been inactive for 2 years now, with pending issue and pull requests.

Would you mind if I took it over to continue development, maintenance and so on? I'd be happy to.

You could transfer ownership in npm and I could fork the repo, adding respective credits.

**Comment by WuglyakBolgoink** [comment]
@kaimallea up!

**Comment by gucong3000** [comment]
See: https://www.npmjs.com/policies/disputes

**Comment by DiegoRBaquero** [comment]
goo.gl is however being slowly killed :/

I'm creating a shortener service :D

**Comment by DiegoRBaquero** [comment]
Everyone, here you go: https://github.com/DiegoRBaquero/node-dinli
